mysql:
    host: localhost
    user: testuser
    password: testpassword
    database: testdatabase
aws:
    region: ap-northeast-1
    s3:
        bucket: testbucket
        path: path/to/key
mail:
    admin_name: hoge
    admin_mail: hoge@example.com
    from:
        - hoge@example.com
    send_to:
        - foo@example.com
        - bar@example.com
